#! /bin/sh
# **************************************************************************
# oivxt-config -- a utility for retrieving configuration information for
# the installed InventorXt library.

me=`echo $0 | sed 's,^.*[/\\],,g'`

usage="\
Usage: $me [OPTIONS]
Options:
  --cppflags
  --ldflags
  --libs
  --datadir
  --ac-subst <keyword>
  --have-feature <keyword>
  --build <program> <sourcefile> [<sourcefile>]...
  --version
  --help | --usage"

version="unknown"

# NOTE: If the first argument is changed in the following variables, it is
# also necessary to update configure.in, since that argument is shifted off.

cppflags="-I/usr/X11R6/include -D_POSIX_SOURCE -D_XOPEN_SOURCE"
ldflags="-L/usr/X11R6/lib"
libs="-lInventorXt -lXm -lInventor -lGL -lXext -lSM -lICE -lX11 -ldl -lXt -lXp -lXmu -lXpm"

datadir="/tmp" # ?

while test $# -gt 0
do
  case $1 in
  --help | --usage)  echo "$usage"    ;;
  --version)         echo "$version"  ;;
  --cppflags)        echo "$cppflags" ;;
  --ldflags)         echo "$ldflags"  ;;
  --libs)            echo "$libs"     ;;
  --datadir)         echo "$datadir"  ;;
  --ac-subst)
    shift
    case $1 in
    GUI)              echo "GTK" ;;
    Gui)              echo "Gtk" ;;
    gui)              echo "gtk" ;;
    EVENT)            echo "GdkEvent *" ;;
    WIDGET)           echo "GtkWidget *" ;;
    COMPONENTHEADER)  echo "" ;;
    *)
      echo >&2 "$me: Invalid AC_SUBST: \"$1\""
      exit 1
      ;;
    esac
    ;;
  --have-feature)
    shift
    case $1 in
    renderarea)             exit 0 ;;
    examinerviewer)         exit 0 ;;
    planeviewer)            exit 0 ;;
    walkviewer)             exit 0 ;;
    flyviewer)              exit 0 ;;
    materiallist)           exit 0 ;;
    materialeditor)         exit 0 ;;
    materialsliderset)      exit 0 ;;
    lightsliderset)         exit 0 ;;
    transformsliderset)     exit 0 ;;
    directionallighteditor) exit 0 ;;
    printdialog)            exit 0 ;;
    *)                      exit 1 ;;
    esac
    ;;
  --build)
    shift
    program=$1
    shift
    exec g++ \
      $CPPFLAGS $cppflags \
      $LDFLAGS $ldflags \
      -o $program $@ \
      $LIBS $libs
    ;;
  *)
    echo >&2 "$me: Invalid option: \"$1\""
    echo >&2 "$usage"
    exit 1
    ;;
  esac
  shift
done

exit 0

